-----------------Makefile--------------------------------
ABC.exe:main.o biggest3.o factorial.o reverse.o
        gcc -o ABC.exe main.o biggest3.o factorial.o reverse.o
main.o:main.c
        gcc -c main.c
biggest3.o:biggest3.c
        gcc -c biggest3.c
factorial.o:factorial.c
        gcc -c factorial.c
reverse.o:reverse.c
        gcc -c reverse.c

---------------------------------------------------------------------------------------------

-----------------------------biggest3.c------------------------------------------------------
#include <stdio.h>
void big3() {
    double n1, n2, n3;
    printf("Enter three different numbers: ");
    scanf("%lf %lf %lf", &n1, &n2, &n3);

    // if n1 is greater than both n2 and n3, n1 is the largest
    if (n1 >= n2 && n1 >= n3)
        printf("%.2f is the largest number.", n1);

    // if n2 is greater than both n1 and n3, n2 is the largest
    if (n2 >= n1 && n2 >= n3)
        printf("%.2f is the largest number.", n2);

    // if n3 is greater than both n1 and n2, n3 is the largest
    if (n3 >= n1 && n3 >= n2)
        printf("%.2f is the largest number.", n3);

    //return 0;
}
---------------------------------------------------------------------------------------------------

-------------------------------------------------------factorial.c-------------------------------------------------------
#include <stdio.h>
void fact() {
    int n, i;
    unsigned long long fact = 1;
    printf("\n\nEnter an integer: ");
    scanf("%d", &n);

    // shows error if the user enters a negative integer
    if (n < 0)
        printf("Error! Factorial of a negative number doesn't exist.");
    else {
        for (i = 1; i <= n; ++i) {
            fact *= i;
        }
        printf("Factorial of %d = %llu\n", n, fact);
    }

    //return 0;
}
--------------------------------------------------------------------------------------------------------------------------------

----------------------------------------------------------reverse.c----------------------------------------------------------------------
#include <stdio.h>
void rev()
{
  char str[1000], rev[1000];
  int i, j, count = 0;
  printf ("\n enter string to reverse:");
  scanf("%s", str);
  printf("\nString Before Reverse: %s", str);
  //finding the length of the string
  while (str[count] != '\0')
  {
    count++;
  }
  j = count - 1;

  //reversing the string by swapping
  for (i = 0; i < count; i++)
  {
    rev[i] = str[j];
    j--;
  }

  printf("\nString After Reverse: %s\n", rev);
}
-------------------------------------------------------------------------------------------------------------------------------------------


run below command: 
make
